### ISSUE TITLE
Link to a constructor function's prototype

### ISSUE THREAD

**Issue by ziad-saab** [AsaAyers/js-hyperclick#16]
With the following code:

```javascript
function Person(name) {
  this.name = name;
}
Person.prototype.sayName = function() {
  console.log(this.name);
}

var john = new Person('john');
john.sayName();
```

It would be nice if js-hyperclick could link the `sayName` on the last line back to its definition.

**Comment by AsaAyers** [comment]
See my comment on https://github.com/AsaAyers/js-hyperclick/issues/15#issuecomment-173574215

**Comment by brunolemos** [comment]
Any chance you would reconsider that? It's a must for this type of package.

**Comment by AsaAyers** [comment]
Because Javascript is so dynamic it's impossible to get this 100% right. At this point I'm sticking to limiting this project to what can be statically analyzed without any ambiguity. I wrote this to solve my own navigation. If someone has a better plug in that supports property navigation please let me know.

**Comment by brunolemos** [comment]
@ziad-saab are you using something that does it on atom?

**Comment by AsaAyers** [comment]
http://ternjs.net/ seems to be trying to solve this problem. It's complex enough to need to spin up a whole server for analysis that has a client in your editor.

If you'll switch to writing Flow instead of standard JavaScript [Nuclide has jump to definition support](http://nuclide.io/docs/languages/flow/#jump-to-definition)

**Comment by brunolemos** [comment]
Thanks, I'm using atom-ternjs@0.12.2 now, which has this feature working (v0.13 had a bug about it).
