### ISSUE TITLE
Enable to create a separate config file

### ISSUE THREAD

**Issue by hustKiwi** [AsaAyers/js-hyperclick#89]
Hi @AsaAyers , thanks for your awesome plugin, it saved my time. 

I found that you opposed the idea of assigning an implicit base path but provided an alternative ability with a `moduleRoots ` setting in package.json.

If it is possible, could you make it more flexible with a specific setting file? For example, `.js-hyperclick` or a separate file other than setting in the package.json? Due to the reason that some developer teams do not want to contaminate the package.json by importing a new key-value pair which is just for IDE customization, so if js-hyperclick can support an individual config file, it would be helpful to regard it as a personal setting and add it to .gitignore.

It seems @gmpetrov has implemented a sample feature as it is mentioned above. Would you like to consider the suggestion and re-implement the same feature in your master branch?

Refer https://github.com/gmpetrov/js-hyperclick/commit/623356d52abceb091e325f63d5496c5eb6689b17

<!--
Please go read the FAQ in this project's README.md before opening your issue.
--!>

**Comment by AsaAyers** [comment]
`js-hyperclick` is a personal project that solves my problems. I share it under the MIT license in the hopes that if your problems align with my problems, you can use it too. My problem was that I wanted a better way to navigate JavaScript that didn't have type annotations (Flow/TypeScript). When you don't have type annotations, and want static analysis, this basically leaves you with scopes and modules. `js-hyperclick` does not support [property access](https://github.com/AsaAyers/js-hyperclick#can-you-add-support-for-thisdosomething) because they can't be resolved statically.

# 1. This is a configuration of your project

> Due to the reason that some developer teams do not want to contaminate the package.json by importing a new key-value pair which is just for IDE customization.

It is a configuration about your  *project*. It just happens to be a configuration that no two projects can agree on how to configure. I tried an experiment where it tried to read the config from webpack. It didn't work out because I had to execute webpack's config inside Atom (which is not node) and I had a complex project where that didn't work. See: https://github.com/AsaAyers/js-hyperclick/pull/27#issuecomment-244407142

> it would be helpful to regard it as a personal setting and add it to .gitignore.

It is not a personal setting. Your project has the same `moduleRoots` no matter who is looking at it or which editor they're using.

# 2. Lets all use a standard

@nodkz tried to ask about this [on twitter](https://twitter.com/nodkz/status/771735917203689472):
```
I want `moduleResolve` prop in package.json!
@dan_abramov @left_pad @izs @slicknet @zpao 

https://github.com/AsaAyers/js-hyperclick/pull/27 …


```
![](https://pbs.twimg.com/media/CrXBseHW8AE9feC.jpg)


It ends with "For Node may be not a good solution. But all build tools need one source of true. All implements its own solution. It's bad :(". I completely agree, it's not good that all tools implement their own solution. If you want me to change how `moduleRoots` works, you need to go convince other projects to move to a standard, then I will join that standard.

@gmpetrov :wave: Good luck with the fork. This is exactly why I license my open source projects as MIT.
