### ISSUE TITLE
jump to method definition, not exported reference

### ISSUE THREAD

**Issue by dwelle** [AsaAyers/js-hyperclick#93]
# scenario A

```js
// main.js

const { funcB } = require("./helpers"); // when funcB clicked
```

```js
// helpers.js


module.exports = { // jumps here
    funcA () {},    
    funcB () {} // should jump here instead
};
```

# scenario B

```js
// main.js

const { funcA } = require("./helpers"); // when funcA clicked
```

```js
// helpers.js

function funcA () {} // should jump here
function funcB () {}

module.exports = { // instead of here
    funcA, funcB // shouldn't jump here either
};
```

**Comment by AsaAyers** [comment]
If you use ES6 modules (`import` / `export`) then js-hyperclick will behave as you expect. I only support limited backward compatibility with `module.exports` because it's not always possible to know what will be exported without executing the code. I take the simple approach of just looking for a `module.exports =`, and it doesn't matter what's on the right side of the assignment.

```js
// helpers.js

function funcA () {}
function funcB () {}

module.exports = {
    funcA, funcB
};

// I'm not saying it's ever a good idea to do this, but it's possible.
// Even if I tried to track this, I don't know which implementation to jump to.
if (process.env.NODE_ENV !== 'production') {
    module.exports.funcA = function debugFuncA() {    }
}
```


http://2ality.com/2014/09/es6-modules-final.html has a good explanation of ES6 modules and how it compares to CommonJS.

> Being built into the language allows ES6 modules to go beyond CommonJS and AMD (details are explained later):
> * Their structure can be statically analyzed (for static checking, optimization, etc.).

This scenario will behave exactly as you're expecting.

```js
// main.js

import { funcA, funcB } from "./helpers"
```

```js
// helpers.js

function funcA () {} // should jump here
export function funcB () {}

export { funcA };
```

**Comment by dwelle** [comment]
Yea, makes sense. Thanks for help.
